# Generated by Django 2.2.5 on 2020-04-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=200)),
                ('emp_name', models.CharField(max_length=200)),
                ('attend_date', models.DateTimeField(verbose_name='date published')),
                ('attend_status', models.CharField(max_length=1)),
            ],
        ),
    ]
