# Generated by Django 2.2.5 on 2020-04-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_dob', models.DateField(verbose_name='date published')),
                ('emp_gender', models.CharField(max_length=8)),
                ('emp_fname', models.CharField(max_length=50)),
                ('emp_addr', models.CharField(max_length=50)),
                ('emp_position', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_mnumber', models.IntegerField()),
                ('emp_salary', models.IntegerField()),
                ('dept_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=50)),
                ('attend_date', models.DateTimeField(verbose_name='date published')),
                ('attend_status', models.CharField(max_length=1)),
                ('emp_overtime', models.TimeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('emp_id', models.CharField(max_length=10)),
                ('user_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10)),
                ('user_role', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
